name: ci

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - .github/**
      - .gitignore
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]
    paths-ignore:
      - "**.md"
      - .github/**
      - .gitignore

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-test:
    name: Run build & test
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Prepare pre-requisites
        uses: ./.github/actions/prepare
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Style
        run: |
          pnpm style

      - name: Build
        run: |
          pnpm build

      - name: Test
        run: |
          pnpm test
